'''
    WINDOWING

    Assume a function f(x) is defined on all integers.

    Write a decorator function window_average(k) that, for odd k > 0, 
    can decorate a function f such that it returns the average of the k 
    function values centered at x, rounded down to the nearest integer.
    
    E.g.,
        
        g = window_average(3)(f)

    creates a function g that for any integer x returns:
     
        g(x) = floor((f(x - 1) + f(x) + f(x + 1)) / 3).

    Input:  Multiple lines of Python code using the decorator window_average.
            The last line starts with '#eof' (indicating end of file).

    Output: The output generated by executing the input code.

    Example:

      Input:  @window_average(3)
              def f(x):
                  return x ** 3
  
              for x in [0, 1, 2, 5, 10]:
                  print(x, f(x))
              #eof

      Output: 0 0
              1 3
              2 12
              5 135
              10 1020
    
      For e.g. x = 2 the decorated f returns 12, since

        floor(((2 - 1) ** 3 + 2 ** 3 + (2 + 1) ** 3) / 3) = floor(36 / 3) = 12.
              
    Note: The below code already handles reading and executing the input.
'''
from math import floor

def window_average(n):
    def ydre(f):
        def indre(x):
            g=[s-n//2+x for s in range(n)]
            return floor(sum([f(h) for h in g])/n)
        return indre
    return ydre



import sys
code = ''
for line in sys.stdin:
    code += line
    if line.startswith('#eof'):
        break
exec(code)