'''
    COMPANY

    Create two classes, Company and Employee, supporting the follow operations.

        Company(name)
        
    creates a new Company object with the given str name.  
        
        Employee(name, company)

    creates a new Employee object with the given str name and associated with
    the given Company object company. Each Employee object associated with a
    given Company object is assigned a unique number 1, 2, ... when created.

        str(employee)

    returns for a given Employee object employee a string consisting of

       '<employee name>, <company name> (#<employee number>)'
    
    Input:  Multiple lines of Python code using the classes Company and Employee.
            The last line starts with '#eof' (indicating end of file).

    Output: The output generated by executing the input code.
            
    Example:

      Input:  apple = Company('Apple Computer, Inc.')
              
              steve = Employee('Steven Paul Jobs', apple)
              woz = Employee('Stephen Gary Wozniak', apple)
              
              print(steve)
              print(woz)
              
              #eof

      Output: Steven Paul Jobs, Apple Computer, Inc. (#1)
              Stephen Gary Wozniak, Apple Computer, Inc. (#2)

    Note: The below code already handles reading and executing the input.
'''


class Company:
    def __init__(self,name):
        self.i=0
        self.name=name
    def count(self):
        self.i+=1
        return self.i


class Employee:
    def __init__(self,name,company):
        self.name=name
        self.company=company
        self.emNum=company.count()
    def __str__(self):
        return f"{self.name}, {self.company.name} (#{self.emNum})"

import sys
code = ''
for line in sys.stdin:
    code += line
    if line.startswith('#eof'):
        break
exec(code)